"""
Transpile the thesis inverse-dynamics functions (src/scripts/calculate_{D,H,G}_matrix.m)
into simulator/js/core/thesis_dynamics.js, keeping the symbolic expressions verbatim.

    python simulator/tools/m2js.py
"""
import re, os
ROOT = os.path.join(os.path.dirname(__file__), '..', '..')
SRC = os.path.join(ROOT, 'src', 'scripts')
OUT = os.path.join(ROOT, 'simulator', 'js', 'core', 'thesis_dynamics.js')
ARRAYS = ['THETA', 'Omega', 'IMU', 'DIM', 'DIS', 'M', 'I1', 'I2', 'I3']

def convert(fname):
    lines = open(os.path.join(SRC, fname), encoding='latin-1').read().splitlines()
    header = lines[0].strip()
    m = re.match(r'function\s+(\w+)\s*=\s*(\w+)\((.*)\)', header)
    out_var, name, args = m.group(1), m.group(2), [a.strip() for a in m.group(3).split(',')]
    body = []
    for ln in lines[1:]:
        s = ln.split('%', 1)[0].strip()
        if not s or s == 'end':
            continue
        lhs, rhs = [x.strip() for x in s.rstrip(';').split('=', 1)]
        if lhs == out_var:
            rhs = rhs.strip('[]')
            rows = [r.split() for r in rhs.split(';')]
            if all(len(r) == 1 for r in rows):
                body.append('return [' + ', '.join(r[0] for r in rows) + '];')
            else:
                body.append('return [' + ', '.join('[' + ', '.join(r) + ']' for r in rows) + '];')
            continue
        for a in ARRAYS:
            rhs = re.sub(r'\b' + a + r'\((\d+)\)', lambda mm: a + '[' + str(int(mm.group(1)) - 1) + ']', rhs)
        rhs = rhs.replace('^', '**')
        rhs = re.sub(r'\bround\(', 'Math.round(', rhs)
        body.append('var ' + lhs + ' = ' + rhs + ';')
    js = '  function ' + name + '(' + ', '.join(args) + ') {\n    var cos = Math.cos, sin = Math.sin;\n'
    js += '\n'.join('    ' + b for b in body) + '\n  }\n'
    return name, js

parts = [convert(f) for f in ['calculate_D_matrix.m', 'calculate_H_matrix.m', 'calculate_G_matrix.m']]
with open(OUT, 'w') as f:
    f.write('/*\n * thesis_dynamics.js - GENERATED by simulator/tools/m2js.py from src/scripts/calculate_{D,H,G}_matrix.m.\n'
            ' * Verbatim port of the symbolic inverse-dynamics expressions used by the Simulink block\n'
            ' * "gimbal_inverted" (Q = D*ACC + H + G). Arrays keep MATLAB linear (column-major) indexing.\n * Do not edit by hand.\n */\n')
    f.write("(function (root) {\n  'use strict';\n  var GS = root.GS = root.GS || {};\n\n")
    for _, js in parts:
        f.write(js + '\n')
    f.write('  GS.thesisDyn = { D: ' + parts[0][0] + ', H: ' + parts[1][0] + ', G: ' + parts[2][0] + ' };\n')
    f.write("})(typeof window !== 'undefined' ? window : globalThis);\n")
print('written', OUT)
